# Generated by Django 2.1 on 2019-01-22 12:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DailyNotificationSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('comment', models.CharField(blank=True, default='', max_length=100)),
                ('operator', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('publication', models.DateTimeField(blank=True, null=True)),
                ('prevent_publication', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('direction', models.BooleanField(default=False)),
                ('sequence', models.IntegerField(default=0)),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('message_id', models.CharField(max_length=200)),
                ('references', models.CharField(blank=True, max_length=400)),
                ('answered', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='problem_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.ProblemClass'),
        ),
        migrations.AddField(
            model_name='historyelement',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.Issue'),
        ),
        migrations.AddField(
            model_name='historyelement',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.State'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.Mail'),
        ),
        migrations.AddField(
            model_name='address',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.Issue'),
        ),
    ]
