# Generated by Django 2.1.3 on 2018-12-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='issue',
        ),
        migrations.AddField(
            model_name='mail',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
