# Generated by Django 2.1.3 on 2019-01-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='direction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
