# Generated by Django 2.1.3 on 2019-03-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='problem_class',
        ),
        migrations.AddField(
            model_name='issue',
            name='problem',
            field=models.CharField(default='empty', max_length=100),
            preserve_default=False,
        ),
    ]
