# Generated by Django 2.1.3 on 2019-01-16 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0002_auto_20190115_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNotificationSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adderss', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='mail',
            name='received_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
