# Generated by Django 2.1.3 on 2019-01-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0003_auto_20190116_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailynotificationsubscriber',
            old_name='adderss',
            new_name='address',
        ),
    ]
