# Generated by Django 2.1.3 on 2019-01-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0005_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='message_id',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
