# Generated by Django 2.1.3 on 2019-01-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0006_mail_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='references',
            field=models.CharField(default='test', max_length=400),
            preserve_default=False,
        ),
    ]
