# Generated by Django 2.1.3 on 2019-01-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0007_mail_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='references',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
