# Generated by Django 2.1.3 on 2019-01-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0008_auto_20190119_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
