# Generated by Django 2.1.3 on 2019-01-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0009_issue_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
