# Generated by Django 2.1.3 on 2019-01-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0010_state_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='comment',
        ),
        migrations.AddField(
            model_name='historyelement',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
