# Generated by Django 2.1.3 on 2019-01-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0011_auto_20190120_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyelement',
            name='operator',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='prevent_publication',
            field=models.BooleanField(default=False),
        ),
    ]
