# Generated by Django 2.1.3 on 2019-01-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0012_auto_20190120_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyelement',
            name='operator',
            field=models.CharField(max_length=100),
        ),
    ]
